### ISSUE TITLE
Doubled VGA clock option?

### ISSUE THREAD

**Issue by toivoh** [TinyTapeout/tt-rp2040-firmware#2]
Would it be possible to add a doubled VGA clock frequency (I guess 50.358 MHz?) to the list of supported clock frequencies? It's tantalizingly close to the current max frequency of 50 MHz and might allow a design to do twice as much per pixel.

**Comment by urish** [comment]
Should probably work with 

```
set-clock 2 1410000000 7 2 1 1
```

Can you please try and report?

**Comment by toivoh** [comment]
Thanks, good to know! I'm not sure what I should try it on though, I don't have a Raspberry Pi.

**Comment by urish** [comment]
It's a Raspberry Pi Pico specifically. You can probably ask someone on the discord to quickly test it for you.
